server:
  port: 8084

spring:
  application:
    name: MyGateway
  config:
    import: "optional:configserver:"
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    sender:
      type: kafka
    baseUrl: http://localhost:9411


logging:
  level.root: ERROR
  level.com.abc.gateway: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [${spring.application.name}] %magenta([%thread]) %highlight(%-5level) %logger{15}.%M - %msg%n"


app:
  gckPhaseActive: true
  detPhaseActive: true
  forwardingMode: false
  forwardingURL: "abc.com"


